= VM Migration with the Ansible Automation Platform

*SAY:*

In the previous module, you saw how easy it is to migrate VMs from VMware to OpenShift Virtualization using the Migration Toolkit for Virtualization.

While this process is effective and doesn’t take too long to complete, how can we speed up the process and achieve scale when needed?

Here, we introduce Ansible Automation Platform (AAP) to the mix.

== Ansible Automation Platform

Lopsum ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus ac nunc ultricies tincidunt. Nullam nec purus ac nunc ultricies tincidunt. Nullam nec purus ac nunc ultricies tincidunt. Nullam nec purus ac nunc ultricies tincidunt.

== Summary

*SAY:*

In this demo, we used the Ansible Automation Platform to migrate our VMs to OpenShift Virtualization, bringing automation to the process and all the benefits that come with it: speed, scale, and consistency.

Furthermore, we can now easily integrate this process with other automation workflows and automate the lifecycle of your virtual machines. While Day 2 and Day 3 operations are not covered in this demo, there are separate resources available to assist you with those.

*DO:*

NOTE: Please delete this demo from the Red Hat Demo Platform as soon as you have completed practicing or delivering the demo to your customer.
